### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by TheHemantKaushik** [shreyanshp/upload-app-browserstack#5]
Example usage text is not correct. Please update:

**FROM:**
uses: actions/upload-app-browserstack@v1 with: app-path: Apps/shreyansh.apk browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }} browserstack-accesskey: ${{ secrets.BROWSERSTACK_ACCESSKEY }}

**TO:**

    - name: Upload APK to BrowserStack
      uses: shreyanshp/upload-app-browserstack@v3
      with:
        app-path: /path-to-apk/app.apk
        browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
        browserstack-accesskey: ${{ secrets.BROWSERSTACK_ACCESSKEY }}

**Comment by shreyanshp** [comment]
Solved in #6 
Thanks @TheHemantKaushik !
